# Generated by Django 4.0.3 on 2023-10-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('style', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('size', models.SmallIntegerField()),
            ],
        ),
    ]
