# Generated by Django 4.0.3 on 2023-10-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('brand', models.CharField(max_length=150)),
                ('size', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('colour', models.CharField(max_length=150)),
                ('style', models.CharField(max_length=150)),
            ],
        ),
    ]
